In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from  sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

In [2]:
df = pd.read_csv("IMDB Dataset.csv")
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [3]:
df.shape

(50000, 2)

In [4]:
df.review.value_counts()

review
Loved today's show!!! It was a variety and not solely cooking (which would have been great too). Very stimulating and captivating, always keeping the viewer peeking around the corner to see what was coming up next. She is as down to earth and as personable as you get, like one of us which made the show all the more enjoyable. Special guests, who are friends as well made for a nice surprise too. Loved the 'first' theme and that the audience was invited to play along too. I must admit I was shocked to see her come in under her time limits on a few things, but she did it and by golly I'll be writing those recipes down. Saving time in the kitchen means more time with family. Those who haven't tuned in yet, find out what channel and the time, I assure you that you won't be disappointed.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        5
Hilarious, clean, light-hearted, and quote-worthy. What else can you ask for in a film? This is my all-time, number one favorite movie. Ever since I was a little girl, I've dreamed of owning a blue van with flames and an observation bubble.<br /><br />The cliché characters in ridiculous situations are what make this film such great fun. The wonderful comedic chemistry between Stephen Furst (Harold) and Andy Tennant (Melio) make up most of my favorite parts of the movie. And who didn't love the hopeless awkwardness of Flynch? Don't forget the airport antics of Leon's cronies, dressed up as Hari Krishnas: dancing, chanting and playing the tambourine--unbeatable! The clues are genius, the locations are classic, and the plot is timeless.<br /><br />A word to the wise, if you didn't watch this film when you were little, it probably won't win a place in your heart today. But nevertheless give it a chance, you may find that "It doesn't matter what you say, it doesn't matter what you do, you've gotta play."                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          4
Robert Jordan is a television star. Robert Jordan likes things orderly, on time and properly executed. In his world children are to be seen, not heard. So why would Mr. Jordan want to become the master of a rambunctious band of Boy Scouts? Ratings. His staff figures that if learns how to interact with the youth, they will be more inclined to watch his show. Of course watching Jordan cope comprises most of the fun.<br /><br />Like Mr. Belvedere and Mr. Belvedere Goes to College this one is sure to please.<br /><br />ANYONE INTERESTED IN OBTAINING A COPY OF THIS FILM PLEASE WRITE TO ME AT: IAMASEAL2@YAHOO.COM                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          3
You do realize that you've been watching the EXACT SAME SHOW for eight years, right? I could understand the initial curiosity of seeing strangers co-exist on an Island, but you'd think that after watching unkempt, stink-ladened heroes run roughshod through the bush with an egg on a spoon for half a decade would be enough to get you to commit to something a little more original (and interesting).<br /><br />And I'm not even speaking of the shows validity which for the record I find questionable. It's just hard to suspend disbelief for "Bushy Bill" eating a rat when the entire crew of producers and camera people are housed in an air conditioned make-shift bio-dome sipping frosty mochcinno's with moxy.<br /><br />What's the appeal here? I don't care about these people or their meandering lives. I just don't get it. But if you DO find yourself being captivated by hairy, unwashed people, I suggest you turn off your TV and just take a trip to your local bus station where you can see people like this in their TRUE habitat. They call them HOMELESS PEOPLE, and free of charge, you can sit back and marvel in their uncanny ability to retrieve various cigarette debris from a plethora of garbage canisters, eventually striking "pay-dirt" and fashioning a homemade Dr. Frankenstein-styled cancer-stick, all the while begging people for change for food when the stink of "Aqua Velva" on their breath is enough to suggest otherwise. And the best part? Much like Survivor, every week one member of the tribe "Leaves" the "Island" when they are unceremoniously sent packing to the local Institution when the frightening unmedicated state of full-blown schizophrenia kicks into gear! Now THAT'S ENTERTAINMENT!    3
How has this piece of crap stayed on TV this long? It's terrible. It makes me want to shoot someone. It's so fake that it is actually worse than a 1940s sci-fi movie. I'd rather have a stroke than watch this nonsense. I remember watching it when it first came out. I thought, hey this could be interesting, then I found out how absolutely, insanely, ridiculously stupid it really was. It was so bad that I actually took out my pocket knife and stuck my hand to the table.<br /><br />Please people, stop watching this and all other reality shows, they're the trash that is jamming the networks and canceling quality programming that requires some thought to create.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        3
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ..
I thought this movie did a down right good job. It wasn't as creative or original as the first, but who was expecting it to be. It was a whole lotta fun. the more i think about it the more i like it, and when it comes out on DVD I'm going to pay the money for it very proudly, every last cent. Sharon Stone is great, she always is, even if her movie is horrible(Catwoman), but this movie isn't, this is one of those movies that will be underrated for its lifetime, and it will probably become a classic in like 20 yrs. Don't wait for it to be a classic, watch it now and enjoy it. Don't expect a masterpiece, or something thats gripping and soul touching, just allow yourself to get out of your life and get yourself involved in theirs.<br /><br />All in all, this movie is entertaining and i recommend people who haven't seen it see it, because what the critics and box office say doesn't always count, see it for yourself, you never know, you might just enjoy it. I tip my hat to this movie<br /><br />8/10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                1
Bad plot, bad dialogue, bad acting, idiotic directing, the annoying porn groove soundtrack that ran continually over the overacted script, and a crappy copy of the VHS cannot be redeemed by consuming liquor. Trust me, because I stuck this turkey out to the end. It was so pathetically bad all over that I had to figure it was a fourth-rate spoof of Springtime for Hitler.<br /><br />The girl who played Janis Joplin was the only faint spark of interest, and that was only because she could sing better than the original.<br /><br />If you want to watch something similar but a thousand times better, then watch Beyond The Valley of The Dolls.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              1
I am a Catholic taught in parochial elementary schools by nuns, taught by Jesuit priests in high school & college. I am still a practicing Catholic but would not be considered a "good Catholic" in the church's eyes because I don't believe certain things or act certain ways just because the church tells me to.<br /><br />So back to the movie...its bad because two people are killed by this nun who is supposed to be a satire as the embodiment of a female religious figurehead. There is no comedy in that and the satire is not done well by the over acting of Diane Keaton. I never saw the play but if it was very different from this movies then it may be good.<br /><br />At first I thought the gun might be a fake and the first shooting all a plan by the female lead of the four former students as an attempt to demonstrate Sister Mary's emotional and intellectual bigotry of faith. But it turns out the bullets were real and the story has tragedy...the tragedy of loss of life (besides the two former students...the lives of the aborted babies, the life of the student's mom), the tragedy of dogmatic authority over love of people, the tragedy of organized religion replacing true faith in God. This is what is wrong with today's Islam, and yesterday's Judaism and Christianity.                                                                                                                                                                                                                                                                                                                                                                                                                                                1
I'm going to have to disagree with the previous comment and side with Maltin on this one. This is a second rate, excessively vicious Western that creaks and groans trying to put across its central theme of the Wild West being tamed and kicked aside by the steady march of time. It would like to be in the tradition of "Butch Cassidy and the Sundance Kid", but lacks that film's poignancy and charm. Andrew McLaglen's direction is limp, and the final 30 minutes or so are a real botch, with some incomprehensible strategy on the part of heroes Charlton Heston and Chris Mitchum. (Someone give me a holler if you can explain to me why they set that hillside on fire.) There was something callous about the whole treatment of the rape scene, and the woman's reaction afterwards certainly did not ring true. Coburn is plenty nasty as the half breed escaped convict out for revenge, but all of his fellow escapees are underdeveloped (they're like bowling pins to be knocked down one by one as the story lurches forward). Michael Parks gives one of his typically shifty, lethargic, mumbling performances, but in this case it was appropriate as his modern style sheriff symbolizes the complacency that technological progress can bring about.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              1
If you like original gut wrenching laughter you will like this movie. If you are young or old then you will love this movie, hell even my mom liked it.<br /><br />Great Camp!!!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                1
Name: count, Length: 49582, dtype: int64

In [5]:
df['Category'] = df['sentiment'].apply(lambda x:1 if x =='positive' else 0)

In [6]:
df.shape

(50000, 3)

In [7]:
df.head()

                                              review sentiment  Category
0  One of the other reviewers has mentioned that ...  positive         1
1  A wonderful little production. <br /><br />The...  positive         1
2  I thought this was a wonderful way to spend ti...  positive         1
3  Basically there's a family where a little boy ...  negative         0
4  Petter Mattei's "Love in the Time of Money" is...  positive         1

In [8]:
X_train, X_test, y_train, y_test = train_test_split(df.review, df.sentiment, 
                                                    test_size = 0.2)

In [9]:
X_train.shape

(40000,)

In [10]:
X_test.shape

(10000,)

In [11]:
v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 5476609 stored elements and shape (40000, 92878)>

In [12]:
v.vocabulary_

{'own': 59588,
 'this': 82512,
 'movie': 54843,
 'and': 4095,
 'love': 49001,
 'canadian': 12975,
 'movies': 54870,
 'but': 12376,
 'hire': 38395,
 'an': 3978,
 'actress': 2093,
 'like': 48019,
 'rose': 69994,
 'don': 24192,
 'understand': 86062,
 'she': 73707,
 'is': 42634,
 'completly': 17230,
 'useless': 87388,
 'in': 40768,
 'just': 44188,
 'name': 55728,
 'that': 82219,
 'all': 3339,
 'the': 82240,
 'rest': 68566,
 'of': 58057,
 'cast': 13726,
 'good': 34697,
 'enough': 27145,
 'to': 83207,
 'make': 50097,
 'little': 48379,
 'thriller': 82653,
 'work': 91287,
 'was': 89496,
 'surprise': 80086,
 'by': 12478,
 'plot': 62720,
 'which': 90229,
 'not': 57285,
 'first': 30559,
 'time': 82953,
 'it': 42759,
 'used': 87383,
 'those': 82577,
 'unknown': 86578,
 'actors': 2090,
 'did': 22711,
 'very': 88193,
 'well': 89940,
 'even': 28055,
 'jergen': 43448,
 'big': 9093,
 'fan': 29249,
 'his': 38415,
 'liked': 48023,
 'him': 38308,
 'if': 40183,
 'you': 92164,
 'got': 34884,
 'chance': 14439,
 'see': 72688,
 'go': 34429,
 'for': 31394,
 'as': 5562,
 'there': 82359,
 'weren': 90006,
 'floating': 31003,
 'around': 5367,
 'at': 5918,
 'already': 3539,
 'we': 89701,
 'have': 37247,
 'here': 37913,
 'another': 4437,
 'lame': 46568,
 'godfather': 34495,
 'clone': 16215,
 'from': 32266,
 'director': 23062,
 'il': 40269,
 'consigliori': 17846,
 '1973': 488,
 'had': 36312,
 'watched': 89557,
 'earlier': 25621,
 'year': 91941,
 'marquee': 50912,
 'value': 87667,
 'roped': 69956,
 'telly': 81765,
 'savalas': 71519,
 'who': 90390,
 'belatedly': 8387,
 'enters': 27235,
 'proceedings': 64402,
 'seen': 72721,
 'behind': 8328,
 'rather': 66569,
 'campily': 12944,
 'tending': 81862,
 'flowers': 31100,
 'wearing': 89735,
 'beret': 8669,
 'style': 79158,
 'french': 32073,
 'painters': 59811,
 'apart': 4705,
 'looking': 48771,
 'minimally': 53277,
 'sicilian': 74470,
 'he': 37362,
 'sports': 77421,
 'no': 56960,
 'accent': 1792,
 'any': 4647,
 'kind': 45279,
 'other': 58986,
 'than': 82192,
 'familiar': 29227,
 'drawl': 24740,
 'antonio': 4604,
 'sabato': 70652,
 'then': 82314,
 'makes': 50107,
 'unlikely': 86602,
 'gangster': 33000,
 'being': 8351,
 'resistible': 68478,
 'leading': 47197,
 'man': 50321,
 'relationship': 67795,
 'with': 90942,
 'becomes': 8123,
 'paternal': 60564,
 'flick': 30920,
 'eye': 28872,
 'also': 3548,
 'unconvincing': 85880,
 'especially': 27753,
 'since': 74824,
 'subsequently': 79311,
 'romantically': 69837,
 'involved': 42440,
 'latter': 46967,
 'spirited': 77230,
 'teenage': 81631,
 'niece': 56704,
 'besides': 8815,
 'precious': 63802,
 'action': 2059,
 'speak': 76958,
 'none': 57094,
 'way': 89667,
 'memorable': 52275,
 'though': 82582,
 'finale': 30372,
 'set': 73224,
 'clinic': 16152,
 'handled': 36716,
 'furthermore': 32600,
 'score': 72176,
 'francesco': 31830,
 'de': 20822,
 'masi': 51084,
 'serviceable': 73204,
 'nothing': 57313,
 'else': 26487,
 'incidentally': 40891,
 'bargain': 7466,
 'basement': 7644,
 'dvd': 25449,
 'rented': 68107,
 'starts': 78003,
 'off': 58063,
 'midway': 52926,
 'through': 82683,
 'credits': 19247,
 'so': 76116,
 'members': 52259,
 'or': 58655,
 'film': 30284,
 'title': 83140,
 'ever': 28079,
 'listed': 48304,
 'my': 55467,
 'personal': 61426,
 'opinion': 58570,
 'think': 82469,
 'greatest': 35290,
 'video': 88346,
 'game': 32928,
 'created': 19210,
 'played': 62584,
 'friends': 32171,
 'house': 39317,
 'years': 91953,
 'ago': 2778,
 'next': 56580,
 'day': 20769,
 'went': 89991,
 'out': 59054,
 'close': 16230,
 'seven': 73269,
 'stopped': 78577,
 'playing': 62600,
 'can': 12971,
 'help': 37762,
 'get': 33730,
 'bored': 10623,
 've': 87892,
 'been': 8193,
 'addicted': 2173,
 'games': 32943,
 'on': 58378,
 'much': 54969,
 'newer': 56513,
 'systems': 80748,
 'keep': 44802,
 'coming': 16941,
 'back': 6774,
 'more': 54464,
 'goldeneye': 34590,
 'every': 28105,
 'mission': 53624,
 'amazingly': 3716,
 'fun': 32479,
 'challenging': 14401,
 'multi': 55106,
 'player': 62585,
 'mode': 53868,
 'hope': 39050,
 'be': 7934,
 'fortunate': 31654,
 'four': 31729,
 'because': 8092,
 'brothers': 11668,
 'would': 91403,
 'together': 83275,
 'play': 62575,
 'dr': 24619,
 'mordrid': 54462,
 'what': 90134,
 'say': 71588,
 'jeffrey': 43369,
 'combs': 16880,
 'has': 37103,
 'done': 24218,
 'again': 2692,
 'br': 10942,
 'anton': 4590,
 'earth': 25651,
 '100': 51,
 'waiting': 89205,
 'kabal': 44278,
 'evil': 28145,
 'sorcerer': 76601,
 'come': 16889,
 'kill': 45212,
 'train': 83955,
 'kids': 45158,
 'knows': 45685,
 'tricks': 84467,
 'bit': 9378,
 'confusing': 17640,
 'begin': 8276,
 'soon': 76547,
 'feel': 29762,
 'part': 60363,
 'won': 91119,
 'give': 34136,
 'away': 6539,
 'ending': 26942,
 'watch': 89549,
 'doctor': 23950,
 'found': 31708,
 'enjoyable': 27094,
 'doesn': 24025,
 'lot': 48911,
 'violence': 88585,
 'nor': 57171,
 'sexual': 73342,
 'scenes': 71790,
 'focused': 31219,
 'find': 30397,
 'best': 8834,
 'films': 30338,
 'are': 5154,
 'ones': 58406,
 'where': 90207,
 'times': 82977,
 'seems': 72720,
 'fly': 31172,
 'engrossed': 27062,
 'fantasticly': 29332,
 'engrossing': 27064,
 '20': 555,
 '10': 50,
 'worth': 91383,
 'seeing': 72702,
 'bother': 10745,
 'looks': 48776,
 'tired': 83088,
 'acting': 2055,
 'old': 58267,
 'fashioned': 29486,
 'characters': 14563,
 'drab': 24623,
 'should': 74202,
 'studied': 79049,
 'instead': 41803,
 'really': 66839,
 'horrible': 39144,
 'waste': 89531,
 'stereotypes': 78275,
 'clichés': 16095,
 'nonsense': 57126,
 'amateurish': 3696,
 'making': 50116,
 'unbelievable': 85728,
 'awe': 6542,
 'mouth': 54816,
 'wide': 90496,
 'open': 58528,
 'how': 39371,
 'could': 18756,
 'such': 79443,
 'made': 49777,
 'interestingly': 42021,
 'anyone': 4661,
 'funny': 32543,
 'watchable': 89552,
 'sloppy': 75574,
 'junior': 44145,
 'high': 38190,
 'skit': 75200,
 'except': 28290,
 'study': 79059,
 'ancient': 4089,
 'abbott': 1505,
 'costello': 18691,
 'laurel': 47044,
 'hardy': 36932,
 'bad': 6861,
 'maybe': 51472,
 'laugh': 46996,
 'some': 76428,
 'they': 82413,
 'one': 58399,
 'goes': 34537,
 'corner': 18485,
 'pleasure': 62658,
 'bear': 7990,
 'festival': 30023,
 'audience': 6170,
 'award': 6532,
 'deserved': 22127,
 'boy': 10904,
 'door': 24310,
 'short': 74155,
 'script': 72351,
 'written': 91538,
 'keeps': 44808,
 'things': 82467,
 'escalating': 27676,
 'great': 35287,
 'current': 19952,
 'suspense': 80176,
 'coursing': 18877,
 'know': 45669,
 'going': 34563,
 'happen': 36833,
 'main': 50017,
 'character': 14542,
 'tries': 84481,
 'deal': 20855,
 'realization': 66827,
 'new': 56496,
 'neighbor': 56272,
 'might': 52947,
 'most': 54664,
 'ideal': 40085,
 'person': 61420,
 'living': 48419,
 'across': 2043,
 'jokes': 43804,
 'quick': 65801,
 'unexpected': 86245,
 'us': 87366,
 'guessing': 35849,
 'dialog': 22590,
 'feels': 29769,
 'real': 66807,
 'thought': 82584,
 'direction': 23053,
 'rate': 66559,
 'travis': 84263,
 'davis': 20741,
 'shows': 74266,
 'potential': 63552,
 'world': 91325,
 'studio': 79052,
 'comedies': 16900,
 'small': 75682,
 'praise': 63713,
 'considering': 17842,
 'lead': 47187,
 'actor': 2087,
 'do': 23909,
 'triple': 84544,
 'duty': 25429,
 'writing': 91535,
 'directing': 23052,
 'starring': 77981,
 'itunes': 42815,
 'download': 24561,
 'll': 48451,
 'loud': 48937,
 'few': 30078,
 'shorts': 74182,
 'offer': 58092,
 'these': 82390,
 'days': 20786,
 'when': 90202,
 'sat': 71378,
 'down': 24542,
 'cinema': 15633,
 'expecting': 28551,
 'sort': 76645,
 'stylish': 79167,
 'tongue': 83436,
 'cheek': 14813,
 'implied': 40628,
 'trailers': 83950,
 'however': 39385,
 'quickly': 65811,
 'became': 8088,
 'apparent': 4815,
 'trying': 84823,
 'normally': 57207,
 'approve': 4965,
 'try': 84819,
 'entertain': 27237,
 'many': 50612,
 'ways': 89683,
 'possible': 63475,
 'instance': 41793,
 'mix': 53739,
 'comedy': 16902,
 'romance': 69820,
 'lightheartedness': 47994,
 'gritty': 35549,
 'seriousness': 73160,
 'once': 58384,
 'approach': 4949,
 'look': 48763,
 'batman': 7793,
 'forever': 31501,
 'pleasantly': 62638,
 'surprised': 80087,
 'case': 13658,
 'pulled': 65210,
 'end': 26911,
 'result': 68618,
 'highly': 38217,
 'entertaining': 27245,
 'appeal': 4826,
 'mature': 51372,
 'cinemagoers': 15637,
 'weak': 89702,
 'stomach': 78518,
 'warned': 89443,
 'two': 85271,
 'robert': 69562,
 'carlyle': 13433,
 'jonny': 43853,
 'lee': 47320,
 'miller': 53111,
 'pull': 65209,
 'brilliant': 11430,
 'double': 24469,
 'act': 2048,
 'ken': 44875,
 'stott': 78644,
 'does': 24023,
 'excellent': 28282,
 'villain': 88487,
 'mixed': 53740,
 'superb': 79768,
 'costumes': 18707,
 'decent': 21027,
 'let': 47666,
 'me': 51865,
 'having': 37262,
 'gentleman': 33569,
 'highwayman': 38233,
 'opportunity': 58598,
 'dialogue': 22594,
 'definitely': 21326,
 'lacking': 46376,
 'punchiness': 65262,
 'were': 90003,
 'belly': 8479,
 'laughs': 47007,
 'okay': 58223,
 'lines': 48184,
 'terrible': 82004,
 'highlight': 38212,
 'problem': 64383,
 'recent': 67023,
 'british': 11497,
 'ignoring': 40230,
 'notable': 57288,
 'exceptions': 28298,
 'screenplays': 72311,
 'today': 83242,
 'still': 78380,
 'relatively': 67799,
 'mediocre': 52022,
 'compared': 17133,
 'hollywood': 38740,
 'efforts': 26038,
 'larry': 46836,
 'buchanan': 11850,
 'yep': 92017,
 'same': 71032,
 'guy': 36135,
 'attack': 6055,
 'creatures': 19228,
 'count': 18793,
 'em': 26533,
 'conspiracy': 17887,
 'about': 1639,
 'marilyn': 50789,
 'monroe': 54229,
 'blame': 9570,
 'adding': 2182,
 'onto': 58450,
 'growing': 35673,
 'pile': 62124,
 'folders': 31262,
 'left': 47355,
 'over': 59250,
 'oliver': 58303,
 'stone': 78530,
 'eh': 26106,
 'grew': 35403,
 'drawer': 24736,
 'beyond': 8951,
 'doors': 24324,
 'working': 91303,
 'definition': 21327,
 'historical': 38439,
 'inaccuracy': 40776,
 'forget': 31522,
 'everything': 28118,
 'knew': 45608,
 'jimi': 43612,
 'hendrix': 37831,
 'janis': 43124,
 'joplin': 43860,
 'jim': 43607,
 'morrison': 54571,
 'says': 71605,
 'lar': 46782,
 'cuz': 20082,
 'three': 82630,
 'names': 55734,
 'rock': 69624,
 '60s': 1055,
 'killed': 45222,
 'government': 34949,
 'subversives': 79397,
 'counter': 18798,
 'productive': 64462,
 'truth': 84812,
 'justice': 44190,
 'american': 3805,
 'sumpthin': 79684,
 'along': 3503,
 'anyway': 4671,
 'people': 61144,
 'chatman': 14701,
 'meryl': 52538,
 'wolf': 91071,
 'eerily': 25988,
 'their': 82282,
 'life': 47934,
 'shadows': 73424,
 'completely': 17217,
 'your': 92191,
 'eyes': 28899,
 'turn': 85067,
 'backs': 6819,
 'walk': 89259,
 'five': 30637,
 'miles': 53042,
 'them': 82297,
 'show': 74231,
 'recorded': 67169,
 'deaths': 20898,
 'put': 65452,
 'hits': 38487,
 'cannot': 13083,
 'believed': 8419,
 'facts': 29037,
 'stretching': 78856,
 'credibility': 19235,
 'snapping': 75900,
 'point': 62900,
 'ludicrous': 49190,
 'tv': 85161,
 'commercials': 17018,
 'drama': 24677,
 'honestly': 38913,
 'deserve': 22126,
 'twist': 85251,
 'swear': 80356,
 'genius': 33536,
 'said': 70838,
 'roll': 69782,
 'dead': 20826,
 'long': 48720,
 'live': 48395,
 'stars': 77984,
 'describing': 22092,
 'saw': 71562,
 'fond': 31307,
 'memories': 52287,
 'catching': 13837,
 'cinemax': 15671,
 'month': 54305,
 'realized': 66830,
 'discernment': 23188,
 'utterly': 87476,
 'ordinary': 58726,
 'spaghetti': 76845,
 'western': 90041,
 'absolutely': 1694,
 'noteworthy': 57307,
 'photography': 61896,
 'blah': 9546,
 'stick': 78333,
 'sergio': 73140,
 'leone': 47579,
 'westerns': 90048,
 'sarah': 71276,
 'silverman': 74710,
 'her': 37883,
 'worried': 91355,
 'appeared': 4835,
 'humor': 39638,
 'true': 84755,
 'colors': 16817,
 'shine': 73943,
 'central': 14198,
 'gem': 33443,
 'possibly': 63476,
 'par': 60120,
 'likes': 48035,
 'amy': 3968,
 'sedaris': 72660,
 'strangers': 78724,
 'candy': 13034,
 'sociopath': 76195,
 'comparable': 17127,
 'jerri': 43476,
 'blank': 9596,
 'downfall': 24550,
 'its': 42804,
 'supporting': 79959,
 'sister': 74968,
 'ultimately': 85537,
 'meant': 51909,
 'steal': 78108,
 'extremely': 28838,
 'sub': 79203,
 'comparison': 17137,
 'glad': 34159,
 'given': 34140,
 'unique': 86524,
 'crazy': 19188,
 'sense': 72964,
 'self': 72826,
 'will': 90631,
 'succeed': 79409,
 'appeals': 4830,
 'adults': 2422,
 'matter': 51340,
 'married': 50929,
 '26': 708,
 'empathize': 26743,
 'patrick': 60624,
 'warburton': 89393,
 'loves': 49029,
 'wife': 90542,
 'assumes': 5826,
 'enjoy': 27092,
 'monotone': 54219,
 'delivery': 21549,
 'never': 56479,
 'gets': 33741,
 'too': 83464,
 'excited': 28321,
 'low': 49044,
 'nice': 56623,
 'ensemble': 27182,
 'addition': 2185,
 'monday': 54099,
 'night': 56748,
 'line': 48169,
 'up': 87182,
 'david': 20728,
 'spade': 76839,
 'role': 69773,
 'enjoyed': 27096,
 'doses': 24436,
 'trolling': 84639,
 'women': 91115,
 'pilot': 62153,
 'forward': 31665,
 'series': 73153,
 'develops': 22406,
 'iraq': 42503,
 'right': 69219,
 'now': 57399,
 'doing': 24086,
 'job': 43689,
 'gives': 34143,
 'plenty': 62682,
 'watching': 89564,
 'access': 1813,
 'pirated': 62301,
 'came': 12872,
 '11': 111,
 'easily': 25677,
 'worst': 91381,
 'reviews': 68864,
 'claim': 15817,
 'take': 80964,
 'itself': 42805,
 'seriously': 73159,
 'cover': 18922,
 'fact': 29021,
 'writers': 91527,
 'improving': 40734,
 'blade': 9535,
 'notch': 57294,
 'above': 1643,
 'vampire': 87682,
 'assassin': 5729,
 'haven': 37250,
 'recommend': 67125,
 'least': 47251,
 'unbelievably': 85729,
 'harder': 36902,
 'cusp': 20010,
 'redeeming': 67257,
 'qualities': 65647,
 'cliché': 16091,
 'visual': 88707,
 'ie': 40177,
 'opening': 58532,
 'adobe': 2341,
 'premier': 63964,
 'special': 76979,
 'effects': 26011,
 'couldn': 18759,
 'blanks': 9609,
 'guns': 36048,
 'may': 51463,
 'filmed': 30305,
 're': 66744,
 'use': 87382,
 'accurate': 1901,
 'tae': 80880,
 'bo': 10043,
 'class': 15908,
 'picked': 61988,
 'ugly': 85473,
 'chick': 15046,
 'walked': 89261,
 'ron': 69886,
 'hall': 36512,
 'stunt': 79101,
 'folk': 31270,
 'comment': 16992,
 'return': 68759,
 'exactly': 28220,
 'buffy': 11948,
 'slayer': 75373,
 'underworld': 86110,
 'super': 79763,
 'star': 77917,
 'fighting': 30220,
 'vampires': 87685,
 'newest': 56514,
 'genre': 33556,
 'blood': 9839,
 'fake': 29132,
 'screams': 72285,
 'cheesy': 14864,
 'obviously': 57891,
 'wrote': 91555,
 'review': 68858,
 'somehow': 76433,
 'connected': 17718,
 'care': 13335,
 'paid': 59789,
 '33': 802,
 'cents': 14216,
 'wrap': 91448,
 'someone': 76439,
 'semester': 72878,
 'school': 71988,
 'decided': 21041,
 'credit': 19239,
 'better': 8887,
 'course': 18873,
 '12': 138,
 'hour': 39313,
 'nights': 56774,
 'week': 89810,
 'several': 73279,
 'thousand': 82597,
 'half': 36488,
 'hoping': 39066,
 'mortar': 54592,
 'rated': 66562,
 'entertainment': 27247,
 'sure': 80019,
 'epic': 27409,
 'lord': 48852,
 'rings': 69303,
 'gone': 34673,
 'wind': 90724,
 'particularly': 60403,
 'moves': 54841,
 'kelsey': 44863,
 'grammar': 35069,
 'home': 38800,
 'loose': 48815,
 'captain': 13236,
 'diesel': 22748,
 'pitted': 62367,
 'against': 2694,
 'nuclear': 57462,
 'navy': 56059,
 'war': 89382,
 'designed': 22144,
 'terrorists': 82040,
 'bomb': 10321,
 'our': 59042,
 'defenses': 21276,
 'kinda': 45280,
 'ironic': 42550,
 'pre': 63763,
 '911': 1231,
 'topic': 83523,
 'cause': 13955,
 'mostly': 54672,
 'start': 77991,
 'finish': 30442,
 'rob': 69539,
 'schneider': 71959,
 '2nd': 756,
 'command': 16951,
 'frank': 31865,
 'burns': 12260,
 'pulls': 65218,
 'others': 58989,
 'perfect': 61228,
 'parts': 60430,
 'rip': 69334,
 'torn': 83588,
 'bruce': 11710,
 'dern': 22038,
 'plain': 62462,
 'simple': 74775,
 '90': 1218,
 'minutes': 53357,
 'need': 56191,
 'pick': 61983,
 'prude': 64935,
 'language': 46714,
 'innuendo': 41637,
 'rent': 68102,
 'buy': 12439,
 'wish': 90897,
 'tough': 83724,
 'critic': 19431,
 'story': 78619,
 'editing': 25898,
 'awful': 6554,
 'halfway': 36502,
 'expect': 28541,
 'based': 7636,
 'something': 76453,
 'aware': 6536,
 'into': 42244,
 'worse': 91362,
 'cuts': 20066,
 'awkward': 6565,
 'points': 62915,
 'unrelated': 86842,
 'previous': 64188,
 'sex': 73314,
 'scene': 71783,
 'middle': 52873,
 'feelings': 29768,
 'toward': 83784,
 'each': 25585,
 'crap': 19097,
 'screen': 72297,
 'disappointed': 23127,
 'pay': 60744,
 'wasting': 89543,
 'money': 54116,
 'anything': 4665,
 'yourself': 92195,
 'favor': 29610,
 'meg': 52086,
 'visits': 88700,
 'mechanic': 51948,
 'piston': 62334,
 'firing': 30544,
 'implying': 40643,
 'poor': 63217,
 'energy': 26988,
 'fiancée': 30113,
 'hilarious': 38261,
 'ryan': 70569,
 'sweet': 80391,
 'wonderful': 91125,
 'lovable': 48998,
 'intelligent': 41929,
 'innocent': 41617,
 'indignant': 41141,
 'expressions': 28718,
 'wishing': 90903,
 'yours': 92194,
 'hero': 37962,
 'handles': 36719,
 'garage': 33043,
 'physicist': 61943,
 'transformation': 84063,
 'einstein': 26165,
 'romantic': 69836,
 'side': 74509,
 'psyche': 65018,
 'puzzle': 65491,
 'round': 70144,
 'front': 32272,
 'press': 64085,
 'awfully': 6557,
 'underrated': 86045,
 'deserves': 22130,
 'accolades': 1841,
 'attempts': 6074,
 'revival': 68891,
 'loses': 48898,
 'vote': 88961,
 'including': 40919,
 'improbable': 40720,
 'far': 29349,
 'fetched': 30035,
 'theory': 82347,
 'bought': 10783,
 'govt': 34961,
 'why': 90460,
 'figure': 30233,
 'top': 83511,
 'century': 14220,
 'presidential': 64076,
 'seal': 72493,
 'approval': 4964,
 'artist': 5521,
 'song': 76507,
 'remember': 67950,
 'words': 91276,
 'ballad': 7110,
 'lyrics': 49501,
 'natures': 55987,
 'telling': 81759,
 'somethings': 76457,
 'wrong': 91540,
 'forgiving': 31539,
 'please': 62645,
 'question': 65776,
 'thanks': 82209,
 'searching': 72530,
 'internet': 42103,
 'mind': 53201,
 'challenge': 14396,
 'able': 1588,
 'mer': 52417,
 'paying': 60757,
 'attention': 6087,
 'stumbled': 79080,
 ...}

In [25]:
clf = Pipeline([
    ('vectorizer', CountVectorizer()),                                                    
    ('random_forest', (RandomForestClassifier(n_estimators=50, criterion='entropy')))      
])

In [14]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()),
                ('random_forest',
                 RandomForestClassifier(criterion='entropy', n_estimators=50))])

In [15]:
y_pred = clf.predict(X_test)

In [16]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

    negative       0.84      0.83      0.84      5000
    positive       0.83      0.84      0.84      5000

    accuracy                           0.84     10000
   macro avg       0.84      0.84      0.84     10000
weighted avg       0.84      0.84      0.84     10000

In [17]:
clf = Pipeline([
                
     ('vectorizer', CountVectorizer()),   
      ('KNN', (KNeighborsClassifier(n_neighbors=10, metric = 'euclidean')))   #using the KNN classifier with 10 neighbors 
])

In [18]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()),
                ('KNN',
                 KNeighborsClassifier(metric='euclidean', n_neighbors=10))])

In [19]:
y_pred = clf.predict(X_test)

In [20]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

    negative       0.65      0.68      0.66      5000
    positive       0.66      0.63      0.65      5000

    accuracy                           0.66     10000
   macro avg       0.66      0.66      0.66     10000
weighted avg       0.66      0.66      0.66     10000

In [21]:
clf = Pipeline([
                
     ('vectorizer', CountVectorizer()),   
      ('Multi NB', MultinomialNB())   #using the Multinomial Naive Bayes classifier 
])

In [22]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()),
                ('Multi NB', MultinomialNB())])

In [23]:
y_pred = clf.predict(X_test)

In [24]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

    negative       0.82      0.87      0.85      5000
    positive       0.87      0.81      0.84      5000

    accuracy                           0.84     10000
   macro avg       0.84      0.84      0.84     10000
weighted avg       0.84      0.84      0.84     10000