In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("spam.csv")
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [6]:
df['spam'] = df['Category'].apply(lambda x: 1 if x =='spam' else 0)

In [7]:
df.shape

(5572, 3)

In [8]:
df.head()

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [10]:
X_train.shape

(4457,)

In [11]:
X_test.shape

(1115,)

In [12]:
type(X_train)

pandas.core.series.Series

In [17]:
X_train[:4]

4580                   No plans yet. What are you doing ?
5412    Gr8. So how do you handle the victoria island ...
1268     SERIOUSLY. TELL HER THOSE EXACT WORDS RIGHT NOW.
2668                   Why de. You looking good only:-)..
Name: Message, dtype: object

In [14]:
type(y_train)

pandas.core.series.Series

In [15]:
y_train[:4]

4580    0
5412    0
1268    0
2668    0
Name: spam, dtype: int64

### Create bag of words representation using CountVectorizer

In [18]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59286 stored elements and shape (4457, 7669)>

In [20]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], shape=(7669,))

In [21]:
X_train_cv.shape

(4457, 7669)

In [22]:
v.get_feature_names_out()[1771]

'chat'

In [23]:
v.vocabulary_

{'no': 4765,
 'plans': 5211,
 'yet': 7624,
 'what': 7402,
 'are': 1068,
 'you': 7637,
 'doing': 2420,
 'gr8': 3207,
 'so': 6236,
 'how': 3507,
 'do': 2400,
 'handle': 3307,
 'the': 6747,
 'victoria': 7211,
 'island': 3728,
 'traffic': 6936,
 'plus': 5233,
 'when': 7408,
 'album': 915,
 'due': 2501,
 'seriously': 5981,
 'tell': 6691,
 'her': 3402,
 'those': 6792,
 'exact': 2703,
 'words': 7520,
 'right': 5738,
 'now': 4812,
 'why': 7429,
 'de': 2211,
 'looking': 4179,
 'good': 3178,
 'only': 4917,
 'hai': 3291,
 'priya': 5383,
 'doctor': 2405,
 'said': 5841,
 'pa': 5013,
 'where': 7411,
 'sian': 6101,
 'aft': 870,
 'meeting': 4400,
 'supervisor': 6561,
 'got': 3196,
 'work': 7521,
 'liao': 4069,
 'working': 7525,
 'going': 3168,
 'out': 4983,
 'to': 6864,
 'buy': 1606,
 'mum': 4620,
 'present': 5353,
 'ar': 1063,
 'hmm': 3438,
 'too': 6902,
 'many': 4324,
 'of': 4865,
 'them': 6754,
 'unfortunately': 7082,
 'pics': 5175,
 'obviously': 4855,
 'arent': 1071,
 'hot': 3495,
 'cakes': 1626,
 'its': 3742,
 'kinda': 3916,
 'fun': 3041,
 'tho': 6791,
 'whenevr': 7410,
 'ur': 7132,
 'sad': 5834,
 'gray': 3225,
 'remembr': 5650,
 'im': 3604,
 'here': 3403,
 'listn': 4127,
 'watevr': 7331,
 'wanna': 7302,
 'say': 5882,
 'jus': 3849,
 'walk': 7290,
 'wid': 7434,
 'me': 4380,
 'little': 4130,
 'while': 7417,
 'amp': 970,
 'promise': 5409,
 'll': 4139,
 'bring': 1534,
 'back': 1217,
 'smile': 6207,
 'sure': 6573,
 'can': 1657,
 'take': 6631,
 'any': 1011,
 'sick': 6104,
 'time': 6833,
 'did': 2324,
 'wake': 7287,
 'up': 7113,
 'on': 4908,
 'my': 4643,
 'own': 5006,
 'gt': 3253,
 'rob': 5761,
 'mack': 4277,
 'his': 3427,
 'gf': 3127,
 'in': 3627,
 'theater': 6750,
 'will': 7446,
 'check': 1779,
 'all': 929,
 'rooms': 5780,
 'befor': 1320,
 'activities': 823,
 'awarded': 1190,
 'city': 1844,
 'break': 1517,
 'and': 980,
 'could': 2056,
 'win': 7449,
 '200': 350,
 'summer': 6545,
 'shopping': 6065,
 'spree': 6361,
 'every': 2680,
 'wk': 7484,
 'txt': 7021,
 'store': 6451,
 '88039': 714,
 'skilgme': 6156,
 'tscs087147403231winawk': 6990,
 'age16': 880,
 '50perwksub': 554,
 'stop': 6443,
 'knowing': 3937,
 'well': 7382,
 'use': 7149,
 'foreign': 2946,
 'stamps': 6382,
 'for': 2943,
 'whatever': 7403,
 'send': 5962,
 'off': 4867,
 'serious': 5980,
 'like': 4090,
 'proper': 5420,
 'tongued': 6896,
 'love': 4207,
 'isn': 3730,
 'decision': 2228,
 'it': 3734,
 'feeling': 2818,
 'if': 3586,
 'we': 7343,
 'decide': 2224,
 'who': 7422,
 'then': 6757,
 'life': 4078,
 'would': 7541,
 'be': 1293,
 'much': 4612,
 'simpler': 6122,
 'but': 1602,
 'less': 4058,
 'magical': 4288,
 'hey': 3411,
 'late': 4000,
 'ah': 889,
 'meet': 4398,
 'at': 1135,
 '945': 746,
 'am': 954,
 'horny': 3487,
 'willing': 7447,
 'live': 4131,
 'local': 4148,
 'text': 6721,
 'reply': 5677,
 'hear': 3370,
 'strt': 6476,
 'from': 3022,
 '150p': 309,
 'per': 5116,
 'msg': 4594,
 'netcollex': 4717,
 'ltdhelpdesk': 4230,
 '02085076972': 11,
 'end': 2599,
 'call': 1633,
 'get': 3117,
 'chance': 1750,
 'plz': 5235,
 'lt': 4228,
 'just': 3850,
 'checking': 1783,
 'searching': 5923,
 'dual': 2496,
 'sim': 6119,
 'mobile': 4518,
 'means': 4387,
 'not': 4798,
 'keep': 3883,
 'plan': 5205,
 'manage': 4310,
 'that': 6743,
 'ok': 4889,
 'finish': 2866,
 'tomorrow': 6889,
 'spend': 6325,
 'evening': 2675,
 'with': 7475,
 'cos': 2048,
 'vewy': 7205,
 'lubly': 4232,
 'xxx': 7588,
 'your': 7639,
 'id': 3574,
 'password': 5076,
 'told': 6880,
 'coming': 1941,
 'wednesday': 7362,
 'haha': 3289,
 'mayb': 4374,
 're': 5551,
 'rite': 5755,
 'know': 3936,
 'da': 2169,
 'being': 1331,
 'liked': 4091,
 'by': 1617,
 'someone': 6251,
 'is': 3724,
 'gd': 3095,
 'lor': 4186,
 'faster': 2797,
 'go': 3159,
 'find': 2862,
 'one': 4912,
 'gals': 3065,
 'our': 4980,
 'group': 3244,
 'attached': 1143,
 'result': 5711,
 'or': 4946,
 '6times': 621,
 'sister': 6140,
 'law': 4015,
 'hope': 3476,
 'having': 3353,
 'great': 3228,
 'month': 4553,
 'saying': 5884,
 'abiola': 776,
 'surprised': 6580,
 'she': 6029,
 'still': 6431,
 'guess': 3262,
 'sent': 5972,
 'email': 2587,
 'soon': 6271,
 'hi': 3414,
 'this': 6784,
 'mandy': 4318,
 'sullivan': 6540,
 'calling': 1646,
 'hotmix': 3499,
 'fm': 2921,
 'chosen': 1832,
 'receive': 5587,
 '5000': 547,
 '00': 0,
 'easter': 2532,
 'prize': 5384,
 'draw': 2462,
 'please': 5222,
 'telephone': 6689,
 '09041940223': 159,
 'claim': 1847,
 'before': 1321,
 '29': 385,
 '03': 13,
 '05': 16,
 'transferred': 6948,
 'else': 2583,
 'trying': 6985,
 'hold': 3452,
 'him': 3423,
 'really': 5571,
 'quite': 5495,
 'funny': 3049,
 'wat': 7324,
 'shd': 6028,
 'haf': 3288,
 'run': 5815,
 'shorter': 6070,
 'distance': 2384,
 'idk': 3583,
 'since': 6125,
 'he': 3358,
 'moved': 4581,
 'butting': 1604,
 'heads': 3363,
 'over': 4998,
 'freedom': 2989,
 'vs': 7261,
 'responsibility': 5704,
 'tired': 6840,
 'have': 3347,
 'other': 4973,
 'shit': 6052,
 'deal': 2213,
 'barely': 1249,
 'keeping': 3884,
 'myself': 4648,
 'together': 6875,
 'once': 4911,
 'gets': 3121,
 'added': 831,
 'donno': 2431,
 'genes': 3106,
 'something': 6256,
 'cool': 2033,
 'practicing': 5319,
 'making': 4305,
 'babies': 1210,
 'happy': 3327,
 'new': 4728,
 'year': 7610,
 'dont': 2432,
 'mean': 4383,
 'intrude': 3698,
 'pls': 5229,
 'let': 4062,
 'tuition': 6998,
 'paid': 5023,
 'last': 3998,
 'semester': 5959,
 'thanks': 6736,
 'come': 1935,
 'room': 5776,
 'cannot': 1667,
 'house': 3503,
 'messy': 4433,
 'eldest': 2576,
 'selected': 5951,
 'later': 4003,
 'don': 2428,
 'network': 4721,
 'urgnt': 7138,
 'sms': 6217,
 'ringtone': 5746,
 'order': 4954,
 'ref': 5612,
 'number': 4826,
 'r836': 5501,
 'charged': 1761,
 '50': 545,
 'should': 6074,
 'tone': 6891,
 'arrive': 1097,
 'customer': 2153,
 'services': 5985,
 '09065069154': 214,
 'most': 4568,
 'people': 5114,
 'town': 6930,
 'sry': 6374,
 'jst': 3835,
 'nw': 4838,
 'came': 1652,
 'home': 3460,
 'lessons': 4061,
 'sch': 5895,
 'white': 7420,
 'fudge': 3036,
 'oreos': 4959,
 'stores': 6452,
 'kallis': 3863,
 'ground': 3243,
 'amla': 962,
 'durban': 2509,
 'reckon': 5597,
 'as': 1105,
 'need': 4702,
 'arrange': 1093,
 'transport': 6950,
 'baby': 1211,
 'jade': 3760,
 'paul': 5087,
 'didn': 2326,
 'remember': 5648,
 'barmed': 1252,
 'want': 7304,
 'talk': 6639,
 'must': 4635,
 'book': 1455,
 'huh': 3530,
 'yoga': 7633,
 'basic': 1260,
 'sunday': 6551,
 'reaching': 5555,
 'message': 4427,
 'bugis': 1577,
 'oso': 4971,
 'near': 4691,
 'everyone': 2684,
 'might': 4445,
 'cancer': 1664,
 'throat': 6804,
 'hurts': 3546,
 'answering': 1003,
 'everyones': 2685,
 'calls': 1647,
 'more': 4560,
 'babysitting': 1215,
 'monday': 4542,
 'seeing': 5941,
 'online': 4915,
 'shop': 6063,
 'asked': 1116,
 'ugh': 7042,
 'outta': 4996,
 'class': 1856,
 'boytoy': 1502,
 'miss': 4482,
 'happened': 3320,
 'step': 6418,
 'way': 7338,
 'congrats': 1991,
 'again': 876,
 'some': 6248,
 'food': 2936,
 'responding': 5701,
 'service': 5984,
 'sex': 5995,
 'video': 7213,
 'chat': 1771,
 'mob': 4516,
 'see': 5939,
 'sexiest': 5996,
 'dirtiest': 2363,
 'girls': 3141,
 'phone': 5157,
 'details': 2297,
 '89070': 723,
 'cancel': 1661,
 'there': 6763,
 'bowls': 1483,
 'worth': 7536,
 'left': 4043,
 'http': 3521,
 'tms': 6860,
 'widelive': 7435,
 'com': 1929,
 'index': 3645,
 'wml': 7493,
 '820554ad0a1705572711': 669,
 'first': 2878,
 'true': 6977,
 'friend': 3007,
 'tyler': 7032,
 'literally': 4128,
 'dubsack': 2497,
 'howz': 3514,
 'persons': 5138,
 'story': 6455,
 'friends': 3008,
 'stay': 6406,
 'fb': 2810,
 'eerie': 2554,
 'nokia': 4775,
 'tones': 6892,
 '4u': 539,
 'rply': 5795,
 'title': 6847,
 '8007': 654,
 'eg': 2559,
 'dracula': 2458,
 'titles': 6848,
 'ghost': 3129,
 'addamsfa': 830,
 'munsters': 4626,
 'exorcist': 2725,
 'twilight': 7016,
 'www': 7570,
 'getzed': 3126,
 'co': 1896,
 'uk': 7048,
 'pobox36504w45wq': 5243,
 'nice': 4739,
 'sheffield': 6032,
 'tom': 6884,
 'air': 901,
 'opinions': 4936,
 'categories': 1716,
 'used': 7150,
 'measure': 4390,
 'ethnicity': 2663,
 'next': 4735,
 'census': 1734,
 'busy': 1601,
 'transcribing': 6945,
 'lifetime': 4081,
 'may': 4373,
 'meaningless': 4386,
 'few': 2831,
 'moments': 4539,
 'spent': 6327,
 'than': 6733,
 'itself': 3743,
 'free': 2987,
 'game': 3068,
 'rayman': 5543,
 'golf': 3173,
 'o2': 4846,
 'games': 3069,
 'arcade': 1065,
 '1st': 339,
 'settings': 5990,
 'post': 5290,
 'save': 5877,
 'activ8': 820,
 'press': 5357,
 'key': 3893,
 'termsapply': 6710,
 'weekend': 7368,
 'thanx': 6740,
 'make': 4301,
 'yo': 7632,
 'solihull': 6245,
 'anything': 1019,
 'shadow': 6006,
 'an': 976,
 'early': 2522,
 'spring': 6362,
 'yay': 7607,
 'al': 912,
 'above': 781,
 'wait': 7283,
 'texting': 6728,
 'gonna': 3177,
 'pay': 5090,
 'ticket': 6821,
 'ya': 7597,
 'went': 7387,
 'rent': 5663,
 'had': 3286,
 'bank': 1240,
 'authorise': 1169,
 'payment': 5097,
 'record': 5600,
 'night': 4746,
 'messages': 4429,
 'missed': 4484,
 'darlin': 2190,
 'kate': 3874,
 'doin': 2418,
 'somethin': 6255,
 'tonight': 6897,
 'pub': 5445,
 'called': 1640,
 'swan': 6591,
 'parents': 5054,
 'drink': 2470,
 'sorry': 6280,
 'was': 7317,
 'thought': 6796,
 'lot': 4193,
 'times': 6834,
 'lil': 4096,
 'noon': 4784,
 'fffff': 2833,
 'kadeem': 3858,
 'far': 2791,
 'gone': 3175,
 'drama': 2459,
 'enough': 2618,
 'family': 2781,
 'struggling': 6478,
 'sun': 6549,
 'strange': 6460,
 'place': 5200,
 'reason': 5575,
 'ego': 2563,
 'invited': 3704,
 'actually': 826,
 'necessity': 4698,
 'very': 7203,
 'reppurcussions': 5681,
 'fuck': 3031,
 'babe': 1208,
 'never': 4725,
 'future': 3054,
 'planned': 5209,
 'today': 6871,
 'best': 1350,
 'enjoy': 2612,
 'contacted': 2009,
 'dating': 2200,
 'landline': 3981,
 '09064017305': 210,
 'pobox75ldns7': 5245,
 'aathi': 768,
 'dear': 2217,
 'wen': 7385,
 'lovable': 4206,
 'bcums': 1290,
 'angry': 984,
 'dnt': 2399,
 'coz': 2074,
 'childish': 1810,
 'showing': 6085,
 'deep': 2236,
 'affection': 863,
 'care': 1682,
 'luv': 4246,
 'kettoda': 3892,
 'manda': 4315,
 'day': 2204,
 'slave': 6172,
 'into': 3696,
 'shell': 6034,
 'unconsciously': 7069,
 'avoiding': 1184,
 'unhappy': 7085,
 'hiya': 3432,
 'hlday': 3434,
 'looked': 4177,
 'horrible': 3488,
 'took': 6903,
 'mo': 4514,
 'hows': 3512,
 'camp': 1654,
 'amrca': 971,
 'thing': 6774,
 'speak': 6309,
 'serena': 5978,
 've': 7190,
 'been': 1315,
 'xchat': 7578,
 'final': 2859,
 'attempt': 1145,
 'contact': 2008,
 '86688': 702,
 'pick': 5171,
 'fone': 2933,
 'dumb': 2504,
 'whats': 7404,
 'hill': 3421,
 'monster': 4552,
 'things': 6775,
 'fine': 2864,
 'though': 6795,
 'comes': 1937,
 'bak': 1227,
 'holiday': 3456,
 't4get2text': 6617,
 'uniform': 7088,
 'okay': 4890,
 'booked': 1456,
 'already': 942,
 'including': 3635,
 'mind': 4456,
 'bedroom': 1313,
 'minute': 4471,
 'sed': 5938,
 'sexy': 5999,
 'mood': 4557,
 'minuts': 4473,
 'latr': 4006,
 'cake': 1625,
 'wife': 7437,
 'luck': 4233,
 'takes': 6634,
 '28th': 383,
 'feb': 2813,
 '06': 19,
 'removal': 5657,
 '87239': 712,
 '08708034412': 90,
 'try': 6984,
 'neva': 4724,
 'mate': 4355,
 'awesome': 1192,
 'couple': 2064,
 'purchase': 5460,
 'stuff': 6490,
 'mail': 4294,
 'po': 5237,
 'box': 1484,
 'beauty': 1301,
 'sleep': 6173,
 'help': 3392,
 'pimples': 5187,
 'college': 1924,
 'excellent': 2707,
 'misundrstud': 4495,
 'frnd': 3014,
 'knw': 3940,
 'hate': 3340,
 'bt': 1565,
 'truth': 6983,
 'urself': 7144,
 'gn': 3155,
 'dad': 2172,
 'wanted': 7306,
 'about': 780,
 'apartment': 1027,
 'start': 6394,
 'omw': 4907,
 'yes': 7621,
 'appt': 1056,
 'garage': 3075,
 'keys': 3895,
 'they': 6770,
 'aren': 1070,
 'bookshelf': 1461,
 'nothing': 4803,
 'frm': 3013,
 'tht': 6812,
 'unknown': 7096,
 'cruisin': 2113,
 'girl': 3138,
 'give': 3143,
 'hour': 3500,
 'thats': 6746,
 'alright': 943,
 'jenny': 3787,
 'sipix': 6135,
 'digital': 2343,
 'camera': 1653,
 '09061221061': 188,
 'delivery': 2257,
 'within': 7477,
 '28days': 382,
 'cs': 2117,
 'box177': 1486,
 'm221bp': 4257,
 '2yr': 428,
 'warranty': 7315,
 '150ppm': 313,
 '16': 319,
 '99': 753,
 'lunch': 4241,
 'str': 6456,
 'down': 2450,
 'ard': 1067,
 'smth': 6222,
 'afternoon': 872,
 'onwords': 4922,
 'mtnl': 4609,
 'problem': 5390,
 'south': 6297,
 'mumbai': 4621,
 'cann': 1665,
 'listen': 4123,
 'siva': 6150,
 'tats': 6656,
 'askd': 1115,
 'lol': 4164,
 'despite': 2291,
 'these': 6765,
 'cramps': 2083,
 'loud': 4202,
 'scream': 5910,
 'minutes': 4472,
 'cause': 1718,
 'gyno': 3282,
 'shoving': 6079,
 'belong': 1338,
 'hello': 3389,
 'lover': 4211,
 'goes': 3164,
 'job': 3806,
 'think': 6776,
 'teasing': 6679,
 'kiss': 3923,
 'across': 814,
 'sea': 5921,
 'project': 5405,
 'centre': 1736,
 'look': 4175,
 'pretty': 5363,
 'wif': 7436,
 'long': 4171,
 'hair': 3293,
 'thk': 6785,
 'cutting': 2163,
 'short': 6067,
 'leh': 4049,
 'todays': 6872,
 'voda': 7245,
 'numbers': 4827,
 'ending': 2601,
 '1225': 285,
 '50award': 549,
 'match': 4352,
 '08712300220': 99,
 'quoting': 5500,
 'code': 1906,
 '3100': 442,
 'standard': 6384,
 'rates': 5536,
 'app': 1036,
 'week': 7366,
 'no1': 4766,
 'txting': 7026,
 'mates': 4356,
 'pobox': 5238,
 '36504': 456,
 'w45wq': 7271,
 'norm150p': 4790,
 'pig': 5183,
 '10': 257,
 'eat': 2534,
 'bit': 1393,
 'accident': 800,
 'a30': 763,
 'divert': 2389,
 'via': 7206,
 'wadebridge': 7276,
 'brilliant': 1531,
 'lots': 4195,
 'gorgeous': 3192,
 'pix': 5196,
 'cumming': 2140,
 'thank': 6735,
 'heard': 3371,
 'helloooo': 3391,
 'sweet': 6599,
 'morning': 4564,
 'welcomes': 7381,
 'full': 3039,
 'joy': 3830,
 'gud': 3258,
 'mrng': 4591,
 'half': 3298,
 'oh': 4884,
 'wi': 7430,
 'nz': 4844,
 'players': 5217,
 'unsold': 7105,
 'does': 2408,
 'operate': 4933,
 'after': 871,
 'available': 1175,
 'winner': 7459,
 'valued': 7179,
 'receivea': 5588,
 '900': 738,
 'reward': 5727,
 '09061701461': 191,
 'kl341': 3929,
 'valid': 7175,
 '12': 281,
 'hours': 3502,
 'trip': 6966,
 'tiring': 6841,
 'uni': 7086,
 'starts': 6397,
 'taking': 6636,
 'modules': 4532,
 'concentrating': 1973,
 'yr': 7646,
 'yup': 7656,
 'comin': 1940,
 'knows': 3939,
 'ain': 899,
 'smokin': 6214,
 'shows': 6088,
 'coveragd': 2072,
 'area': 1069,
 'vasai': 7185,
 'reach': 5552,
 'clock': 1871,
 '100': 258,
 'music': 4632,
 'gift': 3132,
 'vouchers': 7258,
 'starting': 6396,
 'word': 7519,
 '87066': 705,
 'tscs': 6988,
 'idew': 3581,
 'skillgame': 6157,
 '1winaweek': 345,
 '150ppermesssubscription': 312,
 'set': 5988,
 '09096102316': 247,
 'cum': 2138,
 '2moro': 403,
 'jane': 3766,
 'xx': 7585,
 'minmoremobsemspobox45po139wa': 4465,
 'meh': 4405,
 'woke': 7498,
 'waiting': 7286,
 'hmmm': 3439,
 'italian': 3735,
 'boy': 1497,
 'grins': 3236,
 'wun': 7569,
 'believe': 1332,
 'shuhui': 6096,
 '18': 323,
 'days': 2205,
 'euro2004': 2667,
 'kickoff': 3904,
 'kept': 3888,
 'informed': 3659,
 'latest': 4004,
 'news': 4733,
 'results': 5712,
 'daily': 2176,
 'unsubscribe': 7108,
 'euro': 2666,
 '83222': 679,
 'fault': 2804,
 'twice': 7014,
 'table': 6620,
 'occupied': 4857,
 'tree': 6962,
 'building': 1579,
 'because': 1304,
 'coat': 1899,
 'hurry': 3543,
 'wear': 7347,
 'gym': 3279,
 'textbuddy': 6724,
 'guys': 3276,
 '25p': 375,
 'search': 5922,
 'postcode': 5293,
 'gaytextbuddy': 3090,
 'name': 4661,
 '89693': 729,
 '08715500022': 122,
 'rpl': 5794,
 'cnl': 1894,
 'havent': 3350,
 'planning': 5210,
 'lido': 4075,
 '530': 564,
 'show': 6080,
 'wildlife': 7445,
 'want2come': 7305,
 'that2worzels': 6744,
 'wizzle': 7483,
 'man': 4309,
 'squishy': 6370,
 'mwahs': 4642,
 'leave': 4037,
 'put': 5469,
 'paper': 5042,
 'morn': 4562,
 'dis': 2365,
 'frnds': 3015,
 'evn': 2693,
 'married': 4340,
 'person': 5133,
 'ignore': 3591,
 'lose': 4188,
 'evr': 2696,
 'operator': 4934,
 'visit': 7236,
 '80488': 660,
 'biz': 1399,
 '600': 581,
 'anytime': 1021,
 'mins': 4468,
 '400': 485,
 'inclusive': 3636,
 'downloads': 2453,
 'deltomorrow': 2258,
 '08002888812': 55,
 'doctors': 2406,
 'reminds': 5656,
 '2go': 396,
 'lounge': 4203,
 'watch': 7325,
 'resizing': 5693,
 'thinkin': 6778,
 'congratulations': 1993,
 '500': 546,
 'cd': 1725,
 '125gift': 289,
 'guaranteed': 3256,
 'entry': 2629,
 'wkly': 7488,
 'tncs': 6863,
 'ldew': 4023,
 'com1win150ppmx3age16': 1930,
 'done': 2430,
 'costa': 2051,
 'del': 2248,
 'sol': 6244,
 'await': 1186,
 ...}

In [25]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(7669,))

In [26]:
np.where(X_train_np[0]!=0)

(array([1068, 2420, 4765, 5211, 7402, 7624, 7637]),)

In [31]:
X_train[:4][2668]

'Why de. You looking good only:-)..'

In [32]:
X_train_np[0][1771]

np.int64(0)

## Train the naive bayes model

In [33]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [35]:
X_test_cv = v.transform(X_test)

In [36]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       976
           1       0.99      0.91      0.95       139

    accuracy                           0.99      1115
   macro avg       0.99      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115

In [37]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

## Train the model using sklearn pipeline and reduce number of lines of code

In [39]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [40]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [41]:

y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       976
           1       0.99      0.91      0.95       139

    accuracy                           0.99      1115
   macro avg       0.99      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115