In [89]:
from sklearn.feature_extraction.text import TfidfVectorizer

corpus = [
    "Thor is eating pizza, Loki is eating pizza, Ironman ate pizza already",
    "Apple is announcing new iphone tomorrow",
    "Tesla is announcing new model-3 tomorrow",
    "Google is announcing new pixel-6 tomorrow",
    "Microsoft is announcing new surface tomorrow",
    "Amazon is announcing new eco-dot tomorrow",
    "I am eating biryani and you are eating grapes"
]

In [90]:
v = TfidfVectorizer()
transform_output = v.fit_transform(corpus)
print(v.vocabulary_)

{'thor': 25, 'is': 16, 'eating': 10, 'pizza': 22, 'loki': 17, 'ironman': 15, 'ate': 7, 'already': 0, 'apple': 5, 'announcing': 4, 'new': 20, 'iphone': 14, 'tomorrow': 26, 'tesla': 24, 'model': 19, 'google': 12, 'pixel': 21, 'microsoft': 18, 'surface': 23, 'amazon': 2, 'eco': 11, 'dot': 9, 'am': 1, 'biryani': 8, 'and': 3, 'you': 27, 'are': 6, 'grapes': 13}

In [91]:
all_feature_names = v.get_feature_names_out()

for word in all_feature_names:
    indx = v.vocabulary_.get(word)
    print(f"{word} {v.idf_[indx]}")

already 2.386294361119891
am 2.386294361119891
amazon 2.386294361119891
and 2.386294361119891
announcing 1.2876820724517808
apple 2.386294361119891
are 2.386294361119891
ate 2.386294361119891
biryani 2.386294361119891
dot 2.386294361119891
eating 1.9808292530117262
eco 2.386294361119891
google 2.386294361119891
grapes 2.386294361119891
iphone 2.386294361119891
ironman 2.386294361119891
is 1.1335313926245225
loki 2.386294361119891
microsoft 2.386294361119891
model 2.386294361119891
new 1.2876820724517808
pixel 2.386294361119891
pizza 2.386294361119891
surface 2.386294361119891
tesla 2.386294361119891
thor 2.386294361119891
tomorrow 1.2876820724517808
you 2.386294361119891

In [92]:
corpus[:2]

['Thor is eating pizza, Loki is eating pizza, Ironman ate pizza already',
 'Apple is announcing new iphone tomorrow']

### lets do tf-idf on a datset

In [93]:
import pandas as pd

In [94]:
df = pd.read_csv("ecommerceDataset.csv")

In [95]:
print(df.shape)
df.head(50000)

(50424, 2)

,Household,"Paper Plane Design Framed Wall Hanging Motivational Office Decor Art Prints (8.7 X 8.7 inch) - Set of 4 Painting made up in synthetic frame with uv textured print which gives multi effects and attracts towards it. This is an special series of paintings which makes your wall very beautiful and gives a royal touch. This painting is ready to hang, you would be proud to possess this unique painting that is a niche apart. We use only the most modern and efficient printing technology on our prints, with only the and inks and precision epson, roland and hp printers. This innovative hd printing technique results in durable and spectacular looking prints of the highest that last a lifetime. We print solely with top-notch 100% inks, to achieve brilliant and true colours. Due to their high level of uv resistance, our prints retain their beautiful colours for many years. Add colour and style to your living space with this digitally printed painting. Some are for pleasure and some for eternal bliss.so bring home this elegant print that is lushed with rich colors that makes it nothing but sheer elegance to be to your friends and family.it would be treasured forever by whoever your lucky recipient is. Liven up your place with these intriguing paintings that are high definition hd graphic digital prints for home, office or any room."
0,Household,"SAF 'Floral' Framed Painting (Wood, 30 inch x ..."
1,Household,SAF 'UV Textured Modern Art Print Framed' Pain...
2,Household,"SAF Flower Print Framed Painting (Synthetic, 1..."
3,Household,Incredible Gifts India Wooden Happy Birthday U...
4,Household,Pitaara Box Romantic Venice Canvas Painting 6m...
...,...,...
49995,Electronics,iBall Soundwave 2 2.0 Channel Multimedia Speak...
49996,Electronics,Rhobos S10 Wireless Portable Bluetooth Powerfu...
49997,Electronics,JBL Flip 3 Stealth Waterproof Portable Bluetoo...
49998,Electronics,F&D F-203G 2.1 Channel Multimedia Speakers Sys...
49999,Electronics,Sony Extra Bass SRS-XB10 Portable Splash-proof...

In [96]:
df.shape

(50424, 2)

In [97]:
df.Household.value_counts()

Household
Household                 19312
Books                     11820
Electronics               10621
Clothing & Accessories     8671
Name: count, dtype: int64

In [98]:
import numpy as np

In [99]:
import pandas as pd

data = {
    'Category': ['Household']*19312 + 
                ['Books']*11820 + 
                ['Electronics']*10621 + 
                ['Clothing & Accessories']*8671
}

df = pd.DataFrame(data)
print(df['Category'].value_counts())

Category
Household                 19312
Books                     11820
Electronics               10621
Clothing & Accessories     8671
Name: count, dtype: int64

In [100]:
df['Feature'] = np.random.rand(len(df))
X = df[['Feature']]
y = df['Category']

### lets use SMOTE to make this a balanced dataset

In [101]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_res, y_res = smote.fit_resample(X, y)

In [102]:
from collections import Counter
print(Counter(y_res))

Counter({'Household': 19312, 'Books': 19312, 'Electronics': 19312, 'Clothing & Accessories': 19312})

In [103]:
df['label_num'] = df.Category.map({
    'Household': 0,
    'Books': 1,
    'Electronics': 2,
    'Clothing & Accessories': 3
})

df.head(49500)

                     Category   Feature  label_num
0                   Household  0.218228          0
1                   Household  0.923805          0
2                   Household  0.697721          0
3                   Household  0.075566          0
4                   Household  0.008701          0
...                       ...       ...        ...
49495  Clothing & Accessories  0.943359          3
49496  Clothing & Accessories  0.604975          3
49497  Clothing & Accessories  0.504572          3
49498  Clothing & Accessories  0.754906          3
49499  Clothing & Accessories  0.090240          3

[49500 rows x 3 columns]

In [104]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df.Feature,
    df.Category, 
    test_size=0.2,
    random_state=2022,
    stratify=df.Category
)

In [105]:
print("Shape of X_train: ", X_train.shape)
print("Shape of X_test: ", X_test.shape)

Shape of X_train:  (40339,)
Shape of X_test:  (10085,)

In [106]:
X_train.head()

5025     0.249402
46009    0.676515
43491    0.110709
38048    0.541473
49708    0.847474
Name: Feature, dtype: float64

In [107]:
y_train.value_counts()

Category
Household                 15449
Books                      9456
Electronics                8497
Clothing & Accessories     6937
Name: count, dtype: int64

In [108]:
y_test.value_counts()

Category
Household                 3863
Books                     2364
Electronics               2124
Clothing & Accessories    1734
Name: count, dtype: int64

In [110]:

smote = SMOTE()
X_train_bal, y_train_bal = smote.fit_resample(X_train[['feature']], y_train)

X_train_bal, y_train_bal = smote.fit_resample(X_train, y_train)

KeyError: "None of [Index(['feature'], dtype='object')] are in the [index]"